### PR TITLE
Reinsert 1st line comment overwrite

### PR DESCRIPTION
**Pull request by Llisandur**
All of the code to check the first line comment and overwrite it was stripped out. This puts it back in and makes it work with the new line format. It won't overwrite the line in files that haven't been changed.

### CODE REVIEW

**Review by Ampersandrew — CHANGES_REQUESTED** [review]
You have added a lot of commented out code near the end of the commit, this should probably be removed before committing.

**Comment by Ampersandrew** [comment]
Sorry, I've had another look.

You have a comment on line 2974 "# Is it valid for the current file type?", but you don't do any check against file type or anything else.  The code you've commented takes "FACT" "BaseSize|M" and turns it into "FACT:BaseSize" "|M" (for instance). *

Since your %token_FACT_tag is global, you can't check validity for a given file type, all FACTs are accepted as valid for all types.

Same comment for FACTSET, INFO and QUALITY, you can't check if they are valid for a given type with these data structures, but your comments say you are doing that.

Code is acceptable, comment is dodgy or misplaced. If you actually want to restrict subsets of these tags to certain files then that needs more than you have here.

* Or does it take "FACT" "BaseSize" and turn it into "FACT:BaseSize" "". If it's doing the latter, now you have an empty tag at the start of the data structure. I'm not sure if that's going to cause issues, I think all your validation is done at this point. In any case the comment doesn't relate to the code.

**Comment by Llisandur** [comment]
That comment is because I copied the code for the BONUS tag and changed it to work with a different tag. So, someone else's comment that I copied. Looking at it, it seems it should be "# Is it valid for the current token type?" instead. I'll change my stuff to that. It works just fine either way.

**Comment by Ampersandrew** [comment]
Hi Regan.

The point is, every tag you're adding here is globally valid for every
line, is that what you wanted?Is it really suitable to have FACT:Worshipers on an item or an Ability?
What does it mean for a Skillto have Worshipers?

Also every FACT is permissible multiple times on every line, is that
right? what about FACT:Abb?I wouldn't have thought we'd want more than one Abb per line.

--
  Andrew Wilson
  andrew@rivendale.net



On Wed, 5 Dec 2018, at 6:37 PM, Regan Anderson wrote:
> That comment is because I copied the code for the BONUS tag and
> changed it to work with a different tag. So, someone else's comment
> that I copied. Looking at it, it seems it should be "# Is it valid for
> the current token type?" instead. I'll change my stuff to that. It
> works just fine either way.> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/PCGen/pcgen-utilities/pull/21#issuecomment-444594303

**Comment by Ampersandrew** [comment]
The point is, every tag you're adding here is globally valid for every line, is that what you wanted?
Is it really suitable to have FACT:Worshipers on an item or an Ability? What does it mean for a Skill
to have Worshipers?

Also every FACT is permissible multiple times on every line, is that right? what about FACT:Abb?
I wouldn't have thought we'd want more than one Abb per line.

I'm active on slack, chat to me about what this means.

**Comment by Ampersandrew** [comment]
Looks good to me.

**Pull request merged**
